language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0

install:
    - composer self-update --rollback
    - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 
    - mkdir -p build/logs

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - php vendor/bin/coveralls -v
