language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0

install:
    - composer require satooshi/php-coveralls

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 
    - mkdir -p build/logs

script:
    - phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls
