language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0

install:
    - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:~1.0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 
    - mkdir -p build/logs

script:
    - ./vendor/bin/phpunit

after_success:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - php vendor/bin/coveralls -v
